let usersWithGoldSubscriptions = [
    {firstname: 'Alice', areaCode: 44},
    {firstname: 'Bobby', areaCode: 44},
    {firstname: 'Constance', areaCode: 33},
    {firstname: 'David', areaCode: 44},
    {firstname: 'Emmeline', areaCode: 33},
    {firstname: 'Frank', areaCode: 91},
    {firstname: 'Gertrude', areaCode: 1},
    {firstname: 'Harry', areaCode: 33},
    {firstname: 'Ingrid', areaCode: 91},
    {firstname: 'James', areaCode: 44},
    {firstname: 'Kelly', areaCode: 91},
    {firstname: 'Liam', areaCode: 91},
    {firstname: 'Mary', areaCode: 44},
    {firstname: 'Nicholas', areaCode: 91},
    {firstname: 'Olivia', areaCode: 33},
    {firstname: 'Peter', areaCode: 33},
    {firstname: 'Queenie', areaCode: 44},
    {firstname: 'Richard', areaCode: 44},
    {firstname: 'Sally', areaCode: 1},
    {firstname: 'Tim', areaCode: 44},
    {firstname: 'Urvashi', areaCode: 91},
    {firstname: 'Vincent', areaCode: 91},
    {firstname: 'Winifred', areaCode: 52},
    {firstname: 'Xavier', areaCode: 33},
    {firstname: 'Yvonne', areaCode: 44},
    {firstname: 'Zorro', areaCode: 91},
]

export default usersWithGoldSubscriptions