let usersWithGoldSubscriptions = [
    {name: 'Alice', areaCode: 44},
    {name: 'Bobby', areaCode: 44},
    {name: 'Constance', areaCode: 33},
    {name: 'David', areaCode: 44},
    {name: 'Emmeline', areaCode: 33},
    {name: 'Frank', areaCode: 91},
    {name: 'Gertrude', areaCode: 1},
    {name: 'Harry', areaCode: 33},
    {name: 'Ingrid', areaCode: 91},
    {name: 'James', areaCode: 44},
    {name: 'Kelly', areaCode: 91},
    {name: 'Liam', areaCode: 91},
    {name: 'Mary', areaCode: 44},
    {name: 'Nicholas', areaCode: 91},
    {name: 'Olivia', areaCode: 33},
    {name: 'Peter', areaCode: 33},
    {name: 'Queenie', areaCode: 44},
    {name: 'Richard', areaCode: 44},
    {name: 'Sally', areaCode: 1},
    {name: 'Tim', areaCode: 44},
    {name: 'Urvashi', areaCode: 91},
    {name: 'Vincent', areaCode: 91},
    {name: 'Winifred', areaCode: 52},
    {name: 'Xavier', areaCode: 33},
    {name: 'Yvonne', areaCode: 44},
    {name: 'Zorro', areaCode: 91},
]

export default usersWithGoldSubscriptions